goods_name = input("请输入商品名：")
qty        = input("请输入数量：")
price      = input("请输入单价：")
vip_card   = input("请输入会员积分：")
total_qty  = input("请输入数量合计：")
total_money = input("请输入实付金额：")
date       = input("请输入日期：")

print()
print("=" * 16 + "葫芦小卖部" + "=" * 16)
print(f"收银员:大娃\t\t日期:{date}")
print("-" * 40)
print(f"商品名称：\t数量：\t单价：")
print(f"{goods_name}\t\t{qty}\t{price}")
print("-" * 40)
print(f"会员积分:{vip_card}\t数量合计:{total_qty}")
print(f"\t\t\t实付金额:{total_money}")
print("=" * 40)
